import { estimateFit } from './fitEstimator.js';
import { I18N, DEFAULT_LANGUAGE, t as translate, localizeEntity as localizeEntityForState } from './src/i18n/index.js';
import { persistTripSetupPreference as persistTripSetupPreferenceState, persistLanguagePreference as persistLanguagePreferenceState, getPersistedLanguagePreference, cookieValue, setCookie, clearCookie } from './src/state/persistence.js';
import { projectBox, createProjector, rotatePoint3d, createBoxVertices, normalizeYaw, clamp } from './src/visualization/geometry.js';

const VEHICLE_INDEX_PATH = './configs/vehicles/index.json';

const BAG_COLORS = ['#2563eb', '#16a34a', '#f97316', '#9333ea', '#0891b2', '#e11d48', '#ca8a04', '#4f46e5'];
const CUSTOM_BAG_COLOR = '#facc15';
const DEFAULT_SEAT_BACK_ANGLE_DEGREES = 20;
const MAX_SEAT_BACK_ANGLE_DEGREES = 45;
const DEFAULT_USABLE_VOLUME_BUFFER_PERCENT = 10;
const MIN_USABLE_VOLUME_BUFFER_PERCENT = 5;
const MAX_USABLE_VOLUME_BUFFER_PERCENT = 50;
const DEFAULT_MAX_QUANTITY_BY_SIZE = {
  large: 12,
  medium: 24,
  small: 36,
  verySmall: 50
};
const CUSTOM_BAG_ID = 'custom-bag';
const CUSTOM_BAG_MIN_DIMENSIONS_MM = { length: 10, width: 10, height: 10 };
const CUSTOM_BAG_MAX_DIMENSIONS_MM = { length: 2500, width: 2500, height: 2500 };
const state = {
  luggageSet: null,
  vehicles: [],
  vehicleId: '',
  configurationId: '',
  activeView: '3d',
  seatBackEncroachmentAngleDegrees: DEFAULT_SEAT_BACK_ANGLE_DEGREES,
  seatBackEncroachmentInputDegrees: String(DEFAULT_SEAT_BACK_ANGLE_DEGREES),
  usableVolumeBufferPercent: DEFAULT_USABLE_VOLUME_BUFFER_PERCENT,
  usableVolumeBufferInputPercent: String(DEFAULT_USABLE_VOLUME_BUFFER_PERCENT),
  rotation3d: { yaw: 315, pitch: 60 },
  activeOrientationLabel: '',
  language: 'en'
};



const t = (key) => translate(state, key);
const localizeEntity = (entity, key) => localizeEntityForState(state, entity, key);

const $ = (selector) => document.querySelector(selector);
function createEl(tag, { className = '', text = '', attrs = {} } = {}) {
  const el = document.createElement(tag);
  if (className) el.className = className;
  if (text !== '') el.textContent = text;
  Object.entries(attrs).forEach(([key, value]) => el.setAttribute(key, String(value)));
  return el;
}
function setSanitizedMarkup(element, markup) {
  // Markup rendered here is generated by local application code (not user-entered HTML).
  // Keep the assignment isolated in one utility to make future sanitizer swaps easy.
  element.innerHTML = markup;
}
const vehicleSelect = $('#vehicleSelect');
const configurationSelect = $('#configurationSelect');
const seatBackEncroachmentDegreesInput = $('#seatBackEncroachmentDegrees');
const seatBackEncroachmentNote = $('#seatBackEncroachmentNote');
const usableVolumeBufferPercentInput = $('#usableVolumeBufferPercent');
const usableVolumeBufferNote = $('#usableVolumeBufferNote');
const luggageControls = $('#luggageControls');
const resetLuggageButton = $('#resetLuggageButton');
const visualization = $('#visualization');

async function readJson(path) {
  const response = await fetch(path);
  if (!response.ok) throw new Error(`Unable to load ${path}`);
  return response.json();
}

async function loadVehicles() {
  const vehicleIndex = await readJson(VEHICLE_INDEX_PATH);
  return Promise.all(vehicleIndex.files.map((file) => readJson(`./configs/vehicles/${file}`)));
}

function dimensionsLabel(dimensions) {
  return `${Math.round(dimensions.length)} × ${Math.round(dimensions.width)} × ${Math.round(dimensions.height)} mm`;
}

function defaultMaxQuantity(item) {
  const volumeMm3 = item.dimensionsMm.length * item.dimensionsMm.width * item.dimensionsMm.height;
  if (volumeMm3 >= 60_000_000) return DEFAULT_MAX_QUANTITY_BY_SIZE.large;
  if (volumeMm3 >= 20_000_000) return DEFAULT_MAX_QUANTITY_BY_SIZE.medium;
  if (volumeMm3 >= 3_000_000) return DEFAULT_MAX_QUANTITY_BY_SIZE.small;
  return DEFAULT_MAX_QUANTITY_BY_SIZE.verySmall;
}

function maxQuantityForItem(item) {
  return Math.max(1, Number(item.maxQuantity) || defaultMaxQuantity(item));
}

function hasValidCustomBagDimensions(dimensions) {
  return ['length', 'width', 'height'].every((axis) => Number.isFinite(Number(dimensions?.[axis])) && Number(dimensions[axis]) >= CUSTOM_BAG_MIN_DIMENSIONS_MM[axis] && Number(dimensions[axis]) <= CUSTOM_BAG_MAX_DIMENSIONS_MM[axis]);
}

function defaultSeatBackAngleDegrees(zones) {
  return zones.find((zone) => zone.seatBackEncroachment)?.seatBackEncroachment?.angleFromVerticalDegrees ?? 0;
}

function seatBackAngleDegrees(zone) {
  const requested = zone.seatBackEncroachment ? state.seatBackEncroachmentAngleDegrees : (zone.seatBackEncroachment?.angleFromVerticalDegrees ?? DEFAULT_SEAT_BACK_ANGLE_DEGREES);
  return clamp(requested, 0, MAX_SEAT_BACK_ANGLE_DEGREES);
}

function seatBackEncroachmentMmAtHeight(zone, heightMm) {
  return heightMm * Math.tan(seatBackAngleDegrees(zone) * (Math.PI / 180));
}

function hasActiveSeatBackEncroachment(zones) {
  return zones.some((zone) => zone.seatBackEncroachment);
}

function vehicleLabel(vehicle) {
  const make = localizeEntity(vehicle, 'make');
  const model = localizeEntity(vehicle, 'model');
  const bodyStyle = localizeEntity(vehicle, 'bodyStyle');
  return `${make} ${model} (${bodyStyle})`;
}

function cloneLuggageWithQuantities() {
  return {
    ...state.luggageSet,
    items: state.luggageSet.items.map((item) => {
      const requestedQuantity = Math.min(maxQuantityForItem(item), Math.max(0, Number($(`#qty-${item.id}`).value)));
      const quantity = item.id === CUSTOM_BAG_ID && !hasValidCustomBagDimensions(item.dimensionsMm) ? 0 : requestedQuantity;
      return { ...item, quantity };
    }).filter((item) => item.quantity > 0)
  };
}

function defaultVehicle() {
  return state.vehicles.find((vehicle) => vehicle.isDefault) ?? state.vehicles[0];
}

function selectedVehicle() {
  return state.vehicles.find((vehicle) => vehicle.id === state.vehicleId) ?? defaultVehicle();
}

function selectedConfiguration(vehicle = selectedVehicle()) {
  return vehicle.seatConfigurations.find((config) => config.id === state.configurationId) ?? vehicle.seatConfigurations[0];
}

function renderVehicleOptions() {
  vehicleSelect.replaceChildren(...state.vehicles.map((vehicle) => createEl('option', {
    text: vehicleLabel(vehicle),
    attrs: { value: vehicle.id }
  })));
  vehicleSelect.value = state.vehicleId;
}

function renderConfigurationOptions() {
  const vehicle = selectedVehicle();
  configurationSelect.replaceChildren(...vehicle.seatConfigurations.map((config) => createEl('option', {
    text: `${localizeEntity(config, 'label')} · ${config.seatsAvailable} ${t('seats')}`,
    attrs: { value: config.id }
  })));
  if (!vehicle.seatConfigurations.some((config) => config.id === state.configurationId)) {
    state.configurationId = vehicle.seatConfigurations[0].id;
  }
  configurationSelect.value = state.configurationId;
}

function renderBufferControl() {
  usableVolumeBufferPercentInput.value = state.usableVolumeBufferInputPercent;
  usableVolumeBufferNote.textContent = `${t('safetyMarginNote')} (min 5%, max 50%)`;
  const parsed = Number.parseInt(state.usableVolumeBufferInputPercent, 10);
  const outOfBounds = Number.isFinite(parsed) && (parsed < MIN_USABLE_VOLUME_BUFFER_PERCENT || parsed > MAX_USABLE_VOLUME_BUFFER_PERCENT);
  usableVolumeBufferPercentInput.classList.toggle('field-input--out-of-bounds', outOfBounds);
}

function renderSeatBackEncroachmentState() {
  const vehicle = selectedVehicle();
  const config = selectedConfiguration(vehicle);
  const zones = config.cargoZoneIds.map((id) => vehicle.cargoZones.find((zone) => zone.id === id)).filter(Boolean);
  renderSeatBackEncroachmentControl(zones);
  renderBufferControl();
}

function renderSeatBackEncroachmentControl(zones) {
  const hasEncroachment = hasActiveSeatBackEncroachment(zones);
  seatBackEncroachmentDegreesInput.value = state.seatBackEncroachmentInputDegrees;
  seatBackEncroachmentDegreesInput.disabled = !hasEncroachment;
  seatBackEncroachmentNote.textContent = `${t('seatBackNote')} (max ${MAX_SEAT_BACK_ANGLE_DEGREES}°)`;
  const parsed = Number.parseInt(state.seatBackEncroachmentInputDegrees, 10);
  const outOfBounds = Number.isFinite(parsed) && (parsed < 0 || parsed > MAX_SEAT_BACK_ANGLE_DEGREES);
  seatBackEncroachmentDegreesInput.classList.toggle('field-input--out-of-bounds', outOfBounds);
}

function syncSeatBackEncroachmentDefault() {
  const vehicle = selectedVehicle();
  const config = selectedConfiguration(vehicle);
  const zones = config.cargoZoneIds.map((id) => vehicle.cargoZones.find((zone) => zone.id === id)).filter(Boolean);
  const hasEncroachment = hasActiveSeatBackEncroachment(zones);
  state.seatBackEncroachmentAngleDegrees = hasEncroachment ? defaultSeatBackAngleDegrees(zones) : 0;
  state.seatBackEncroachmentInputDegrees = String(state.seatBackEncroachmentAngleDegrees);
}

function resetLuggageQuantities() {
  const customBag = state.luggageSet?.items?.find((item) => item.id === CUSTOM_BAG_ID);
  luggageControls.querySelectorAll('input').forEach((input) => {
    input.value = 0;
  });
  if (customBag) {
    ['height', 'width', 'length'].forEach((axis) => {
      customBag.dimensionsMm[axis] = 0;
    });
  }
  syncCustomBagControlState();
  renderResults();
}

function renderLuggageControls() {
  const quantitiesByItemId = new Map(
    state.luggageSet.items.map((item) => {
      const input = $(`#qty-${item.id}`);
      const value = input ? Number(input.value) : item.quantity;
      return [item.id, Number.isFinite(value) ? Math.max(0, value) : 0];
    })
  );
  const controls = state.luggageSet.items.map((item) => {
    const color = colorForSourceId(item.id);
    const article = createEl('article', { className: 'luggage-item', attrs: { style: `--bag-tint:${color};--bag-panel-bg:${mixWithWhite(color, 0.9)}` } });
    const meta = createEl('div');
    meta.append(createEl('strong', { text: localizeEntity(item, 'label') }));
    const dimensionsAndTypeLabel = `${dimensionsLabel(item.dimensionsMm)} · ${item.shapeType.replace('_', ' ')}`;
    if (item.id !== CUSTOM_BAG_ID) {
      meta.append(createEl('span', { text: dimensionsAndTypeLabel }));
    }
    const label = createEl('label');
    label.append(
      createEl('span', { className: 'sr-only', text: t('quantityFor').replace('{item}', localizeEntity(item, 'label')) }),
      createEl('input', { attrs: { id: `qty-${item.id}`, type: 'number', min: '0', max: String(maxQuantityForItem(item)), step: '1', value: quantitiesByItemId.get(item.id) ?? 0 } })
    );
    article.append(meta, label);
    if (item.id === CUSTOM_BAG_ID) {
      const dims = ['height', 'width', 'length'].map((axis) => {
        const input = createEl('input', {
          attrs: {
            id: `custom-${axis}`,
            type: 'number',
            min: String(CUSTOM_BAG_MIN_DIMENSIONS_MM[axis]),
            max: String(CUSTOM_BAG_MAX_DIMENSIONS_MM[axis]),
            step: '1',
            value: String(Math.round(item.dimensionsMm[axis]))
          }
        });
        const row = createEl('label', { className: 'custom-bag-dimension' });
        row.append(createEl('span', { text: `${axis === 'height' ? 'H' : axis === 'width' ? 'W' : 'D'} (mm)` }), input);
        return row;
      });
      const customDimensions = createEl('div', { className: 'custom-bag-dimensions' });
      customDimensions.append(...dims);
      meta.append(customDimensions);
    }
    return article;
  });
  luggageControls.replaceChildren(...controls);
  luggageControls.querySelectorAll('input').forEach((input) => input.addEventListener('input', renderResults));
  const customBag = state.luggageSet.items.find((item) => item.id === CUSTOM_BAG_ID);
  if (customBag) {
    const qtyInput = $(`#qty-${CUSTOM_BAG_ID}`);
    ['height', 'width', 'length'].forEach((axis) => {
      const input = $(`#custom-${axis}`);
      const updateCustomDimension = () => {
        const parsed = Number.parseInt(input.value, 10);
        const hasValue = Number.isFinite(parsed);
        const isOutOfBounds = !hasValue || parsed < CUSTOM_BAG_MIN_DIMENSIONS_MM[axis] || parsed > CUSTOM_BAG_MAX_DIMENSIONS_MM[axis];
        input.classList.toggle('field-input--out-of-bounds', isOutOfBounds);
        const customBagLocked = input.disabled;
        if (customBagLocked) return;
        customBag.dimensionsMm[axis] = hasValue ? parsed : 0;
        syncCustomBagControlState();
      };
      updateCustomDimension();
      input.addEventListener('input', updateCustomDimension);
    });
    syncCustomBagControlState();
  }
}

function syncCustomBagControlState(result = null) {
  const customBag = state.luggageSet?.items?.find((item) => item.id === CUSTOM_BAG_ID);
  const qtyInput = $(`#qty-${CUSTOM_BAG_ID}`);
  if (!customBag || !qtyInput) return;
  const customBagInResult = Boolean(result) && (
    result.placements.some((placement) => (placement.sourceId ?? placement.itemId?.split('#')[0]) === CUSTOM_BAG_ID)
    || result.unplacedItems.some((item) => (item.sourceId ?? item.id?.split('#')[0]) === CUSTOM_BAG_ID)
  );
  const customBagLocked = customBagInResult || Number(qtyInput.value) > 0;
  ['height', 'width', 'length'].forEach((axis) => {
    const input = $(`#custom-${axis}`);
    if (!input) return;
    input.disabled = customBagLocked;
    const parsed = Number.parseInt(input.value, 10);
    const hasValue = Number.isFinite(parsed);
    const isOutOfBounds = !hasValue || parsed < CUSTOM_BAG_MIN_DIMENSIONS_MM[axis] || parsed > CUSTOM_BAG_MAX_DIMENSIONS_MM[axis];
    input.classList.toggle('field-input--out-of-bounds', isOutOfBounds);
  });
  const hasValidDimensions = hasValidCustomBagDimensions(customBag.dimensionsMm);
  qtyInput.max = String(maxQuantityForItem(customBag));
  qtyInput.disabled = !hasValidDimensions;
  if (!hasValidDimensions) qtyInput.value = '0';
  if (Number(qtyInput.value) > maxQuantityForItem(customBag)) qtyInput.value = String(maxQuantityForItem(customBag));
}

function metricCard(label, value, detail = '', className = '') {
  const card = createEl('article', { className: ['metric', className].filter(Boolean).join(' ') });
  card.append(createEl('span', { text: label }), createEl('strong', { text: value }));
  if (detail) card.append(createEl('small', { text: detail }));
  return card;
}

function colorForSourceId(sourceId) {
  if (sourceId === CUSTOM_BAG_ID) return CUSTOM_BAG_COLOR;
  const uniqueSources = [...new Set(estimateSources().map((item) => item.id))];
  const index = uniqueSources.indexOf(sourceId);
  return BAG_COLORS[(index < 0 ? 0 : index) % BAG_COLORS.length];
}

function colorForPlacement(placement) {
  const source = placement.sourceId ?? placement.itemId.split('#')[0];
  return colorForSourceId(source);
}


function localizedPlacementLabel(entry) {
  const sourceId = entry.sourceId ?? (entry.itemId ? entry.itemId.split('#')[0] : null);
  const item = state.luggageSet?.items?.find((candidate) => candidate.id === sourceId);
  if (item) return localizeEntity(item, 'label');
  if (entry?.label) {
    const directLabel = localizeEntity(entry, 'label');
    if (directLabel !== 'label') return directLabel;
  }
  return entry.label ?? sourceId ?? '';
}

function localizedZoneLabel(label, zoneId) {
  const vehicle = selectedVehicle();
  const zone = vehicle?.cargoZones?.find((candidate) => candidate.id === zoneId);
  if (!zone) return label;
  return localizeEntity(zone, 'label');
}

function estimateSources() {
  return state.luggageSet?.items ?? [];
}

function projectZone(zone, view) {
  const dimensions = zone.dimensionsMm;
  if (view === 'side') return { width: dimensions.length, height: dimensions.height, xLabel: t('length'), yLabel: t('height') };
  if (view === 'front') return { width: dimensions.width, height: dimensions.height, xLabel: t('width'), yLabel: t('height') };
  return { width: dimensions.length, height: dimensions.width, xLabel: t('length'), yLabel: t('width') };
}

function seatEncroachmentOverlay(zone, projection, view, padding, scale) {
  if (view !== 'side' || !hasActiveSeatBackEncroachment([zone]) || !zone.dimensionsMm) return '';

  const floorX = padding + projection.width * scale;
  const topX = padding + Math.max(0, projection.width - seatBackEncroachmentMmAtHeight(zone, zone.dimensionsMm.height)) * scale;
  const floorY = padding + projection.height * scale;
  const topY = padding;
  return `
    <g aria-label="${t('seatEncroachmentEnvelope')}">
      <polygon class="seat-encroachment-area" points="${floorX},${floorY} ${floorX},${topY} ${topX},${topY}" />
      <line class="seat-encroachment-line" x1="${floorX}" y1="${floorY}" x2="${topX}" y2="${topY}" />
    </g>
  `;
}

function seatOutlineFor2dView(projection, view, padding, scale) {
  const seatFill = '#fef3c7';
  const seatStroke = '#92400e';
  const label = t('forwardSeats');

  if (view === 'side') {
    const x = padding + projection.width * scale + 14;
    const floorY = padding + projection.height * scale;
    const seatWidth = Math.min(58, projection.width * scale * 0.18);
    const seatHeight = Math.min(92, projection.height * scale * 0.7);
    const baseHeight = Math.max(12, seatHeight * 0.28);
    return `
      <g class="seat-outline seat-outline--side" aria-label="${label}">
        <path d="M ${x} ${floorY - baseHeight} h ${seatWidth} q 8 0 8 8 v ${baseHeight - 8} h ${-seatWidth - 8} z" fill="${seatFill}" stroke="${seatStroke}" />
        <path d="M ${x + seatWidth * 0.46} ${floorY - baseHeight} l ${seatWidth * 0.18} ${-seatHeight} q 3 -10 14 -7 l ${seatWidth * 0.18} 4 l ${-seatWidth * 0.23} ${seatHeight + 3} z" fill="${seatFill}" stroke="${seatStroke}" />
        <text x="${x + seatWidth / 2}" y="${Math.max(18, floorY - seatHeight - 14)}" text-anchor="middle" class="seat-label">${t('front')}</text>
      </g>
    `;
  }

  if (view === 'front') {
    const cargoX = padding;
    const cargoY = padding;
    const cargoWidth = projection.width * scale;
    const seatWidth = Math.max(42, cargoWidth * 0.26);
    const seatHeight = Math.min(54, projection.height * scale * 0.28);
    const gap = Math.max(14, cargoWidth * 0.08);
    const startX = cargoX + (cargoWidth - seatWidth * 2 - gap) / 2;
    const y = Math.max(8, cargoY - seatHeight - 8);
    return `
      <g class="seat-outline seat-outline--front" aria-label="${label}">
        <rect x="${startX}" y="${y}" width="${seatWidth}" height="${seatHeight}" rx="11" fill="${seatFill}" stroke="${seatStroke}" />
        <rect x="${startX + seatWidth + gap}" y="${y}" width="${seatWidth}" height="${seatHeight}" rx="11" fill="${seatFill}" stroke="${seatStroke}" />
        <text x="${cargoX + cargoWidth / 2}" y="${Math.max(14, y - 6)}" text-anchor="middle" class="seat-label">${t('front')}</text>
      </g>
    `;
  }

  const cargoX = padding;
  const cargoY = padding;
  const cargoWidth = projection.width * scale;
  const cargoHeight = projection.height * scale;
  const seatDepth = Math.min(76, cargoWidth * 0.18);
  const seatWidth = Math.max(44, cargoHeight * 0.28);
  const gap = Math.max(12, cargoHeight * 0.08);
  const startY = cargoY + (cargoHeight - seatWidth * 2 - gap) / 2;
  const x = cargoX + cargoWidth + 14;
  return `
    <g class="seat-outline seat-outline--top" aria-label="${label}">
      <rect x="${x}" y="${startY}" width="${seatDepth}" height="${seatWidth}" rx="12" fill="${seatFill}" stroke="${seatStroke}" />
      <rect x="${x}" y="${startY + seatWidth + gap}" width="${seatDepth}" height="${seatWidth}" rx="12" fill="${seatFill}" stroke="${seatStroke}" />
      <line x1="${cargoX + cargoWidth}" y1="${cargoY}" x2="${cargoX + cargoWidth}" y2="${cargoY + cargoHeight}" class="seat-back-line" />
      <text x="${x + seatDepth / 2}" y="${Math.max(18, startY - 8)}" text-anchor="middle" class="seat-label">${t('front')}</text>
    </g>
  `;
}

function shadeColor(hex, percent) {
  const number = Number.parseInt(hex.replace('#', ''), 16);
  const amount = Math.round(2.55 * percent);
  const red = clamp((number >> 16) + amount, 0, 255);
  const green = clamp(((number >> 8) & 0x00ff) + amount, 0, 255);
  const blue = clamp((number & 0x0000ff) + amount, 0, 255);
  return `#${((1 << 24) + (red << 16) + (green << 8) + blue).toString(16).slice(1)}`;
}

function mixWithWhite(hex, ratio = 0.9) {
  const number = Number.parseInt(hex.replace('#', ''), 16);
  const red = (number >> 16) & 0xff;
  const green = (number >> 8) & 0xff;
  const blue = number & 0xff;
  const blend = (channel) => clamp(Math.round(channel * (1 - ratio) + 255 * ratio), 0, 255);
  return `#${((1 << 24) + (blend(red) << 16) + (blend(green) << 8) + blend(blue)).toString(16).slice(1)}`;
}

function renderZoneSvg(zone, placements, index) {
  const projection = projectZone(zone, state.activeView);
  const padding = state.activeView === 'front' ? 82 : 28;
  const seatGutter = state.activeView === 'front' ? 0 : 112;
  const maxSvgWidth = 720;
  const contentWidth = maxSvgWidth - padding * 2 - seatGutter;
  const scale = Math.min(contentWidth / projection.width, 320 / projection.height);
  const svgWidth = Math.max(360, projection.width * scale + padding * 2 + seatGutter);
  const svgHeight = Math.max(220, projection.height * scale + padding * 2 + 34);
  const seatOutline = seatOutlineFor2dView(projection, state.activeView, padding, scale);
  const encroachmentOverlay = seatEncroachmentOverlay(zone, projection, state.activeView, padding, scale);

  const rects = placements.map((placement) => {
    const box = projectBox(placement, state.activeView);
    const x = padding + box.x * scale;
    const y = padding + (projection.height - box.y - box.height) * scale;
    const width = Math.max(4, box.width * scale);
    const height = Math.max(4, box.height * scale);
    return `
      <g>
        <rect class="luggage-rect" x="${x}" y="${y}" width="${width}" height="${height}" rx="7" fill="${colorForPlacement(placement)}" />
        <title>${localizedPlacementLabel(placement)}: ${dimensionsLabel(placement.orientationMm)}</title>
      </g>
    `;
  }).join('');

  return `
    <article class="zone-card">
      <div class="zone-card__header">
        <strong>${localizeEntity(zone, 'label')}</strong>
        <span>${dimensionsLabel(zone.dimensionsMm)} · ${zone.volumeLitres} L</span>
      </div>
      <svg viewBox="0 0 ${svgWidth} ${svgHeight}" role="img" aria-label="${t('zoneViewAria').replace('{zone}', localizeEntity(zone, 'label')).replace('{view}', state.activeView)}">
        ${seatOutline}
        <rect class="cargo-outline" x="${padding}" y="${padding}" width="${projection.width * scale}" height="${projection.height * scale}" rx="12" fill="#eff6ff" />
        ${encroachmentOverlay}
        ${rects}
        <text x="${padding}" y="${svgHeight - 12}" class="axis-label">${projection.xLabel}: ${projection.width} mm</text>
        <text x="${svgWidth - padding}" y="${svgHeight - 12}" text-anchor="end" class="axis-label">${projection.yLabel}: ${projection.height} mm</text>
      </svg>
      ${placements.length === 0 ? `<p class="empty-zone">${t('noBagsInZone')}</p>` : ''}
    </article>
  `;
}


function createSeatGuideVertices(zone) {
  const dimensions = zone.dimensionsMm;
  const seatDepth = Math.max(90, dimensions.length * 0.12);
  const seatHeight = Math.min(Math.max(360, dimensions.height * 0.82), dimensions.height + 140);
  const seatWidth = dimensions.width * 0.28;
  const gap = dimensions.width * 0.08;
  const startY = (dimensions.width - seatWidth * 2 - gap) / 2;

  return [0, 1].flatMap((index) => createBoxVertices(
    { x: dimensions.length + seatDepth * 0.15, y: startY + index * (seatWidth + gap), z: 0 },
    { length: seatDepth, width: seatWidth, height: seatHeight }
  ));
}

function createSeatEncroachmentWedgeVertices(zone) {
  if (!hasActiveSeatBackEncroachment([zone]) || !zone.dimensionsMm) return [];
  const dimensions = zone.dimensionsMm;
  const topEncroachment = clamp(seatBackEncroachmentMmAtHeight(zone, dimensions.height), 0, dimensions.length);
  const topX = dimensions.length - topEncroachment;
  return [
    { x: dimensions.length, y: 0, z: 0 },
    { x: dimensions.length, y: 0, z: dimensions.height },
    { x: topX, y: 0, z: dimensions.height },
    { x: dimensions.length, y: dimensions.width, z: 0 },
    { x: dimensions.length, y: dimensions.width, z: dimensions.height },
    { x: topX, y: dimensions.width, z: dimensions.height }
  ];
}

function displayYawDegrees(yaw) {
  return Math.round(normalizeYaw(yaw)) % 360;
}

function current3dAngles() {
  return {
    yaw: normalizeYaw(state.rotation3d.yaw) * Math.PI / 180,
    pitch: state.rotation3d.pitch * Math.PI / 180
  };
}

function createProjector(zone, placements, canvasWidth, canvasHeight, padding, extraPoints = []) {
  const dimensions = zone.dimensionsMm;
  const center = { x: dimensions.length / 2, y: dimensions.width / 2, z: dimensions.height / 2 };
  const allPoints = [
    ...createBoxVertices({ x: 0, y: 0, z: 0 }, dimensions),
    ...placements.flatMap((placement) => createBoxVertices(placement.positionMm, placement.orientationMm)),
    ...extraPoints
  ];
  const raw = (point) => rotatePoint3d(point, center);
  const maxRadius = Math.max(...allPoints.map((point) => {
    const centeredX = point.x - center.x;
    const centeredY = point.y - center.y;
    const centeredZ = point.z - center.z;
    return Math.hypot(centeredX, centeredY, centeredZ);
  }), 1);
  const scale = Math.min((canvasWidth - padding * 2) / (maxRadius * 2), (canvasHeight - padding * 2) / (maxRadius * 2));
  return (point) => {
    const output = raw(point);
    return {
      x: canvasWidth / 2 + output.x * scale,
      y: canvasHeight / 2 + output.y * scale,
      depth: output.depth
    };
  };
}

function polygonPoints(points) {
  return points.map((point) => `${point.x.toFixed(1)},${point.y.toFixed(1)}`).join(' ');
}

function renderFace(vertices, indices, fill, className, title = '') {
  const points = indices.map((faceIndex) => vertices[faceIndex]);
  const depth = points.reduce((total, point) => total + point.depth, 0) / points.length;
  return {
    depth,
    markup: `<polygon class="${className}" points="${polygonPoints(points)}" fill="${fill}">${title ? `<title>${title}</title>` : ''}</polygon>`
  };
}

function orientationPresets() {
  return {
    x: { label: t('bootView'), yaw: 270, pitch: 90 },
    y: { label: t('sideView'), yaw: 0, pitch: 90 },
    z: { label: t('topView'), yaw: -90, pitch: 0 }
  };
}

function renderOrientationAxisControl() {
  const origin = { x: 710, y: 104 };
  const axisLength = 44;
  const center = { x: 0, y: 0, z: 0 };
  const axes = [
    { key: 'x', label: 'X', color: '#dc2626', vector: { x: axisLength, y: 0, z: 0 }, title: t('bootView') },
    { key: 'y', label: 'Y', color: '#16a34a', vector: { x: 0, y: axisLength, z: 0 }, title: t('sideView') },
    { key: 'z', label: 'Z', color: '#2563eb', vector: { x: 0, y: 0, z: axisLength }, title: t('topView') }
  ];

  const axisMarkup = axes.map((axis) => {
    const endpoint = rotatePoint3d(axis.vector, center);
    const x = origin.x + endpoint.x;
    const y = origin.y + endpoint.y;
    const labelX = origin.x + endpoint.x * 1.18;
    const labelY = origin.y + endpoint.y * 1.18;

    return `
      <g class="orientation-axis-button" role="button" tabindex="0" data-axis="${axis.key}" aria-label="${t('switchTo').replace('{view}', axis.title)}" style="--axis-color:${axis.color}">
        <line class="orientation-axis-line" x1="${origin.x}" y1="${origin.y}" x2="${x.toFixed(1)}" y2="${y.toFixed(1)}" />
        <circle class="orientation-axis-end" cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="4" />
        <text class="orientation-axis-label" x="${labelX.toFixed(1)}" y="${labelY.toFixed(1)}" text-anchor="middle" dominant-baseline="middle">${axis.label}</text>
        <title>${t('axisTitle').replace('{axis}', axis.label).replace('{view}', axis.title)}</title>
      </g>
    `;
  }).join('');

  const orientationStatus = state.activeOrientationLabel
    ? `<text class="orientation-axis-preset-label" x="722" y="172" text-anchor="middle">${state.activeOrientationLabel}</text>`
    : `<text class="orientation-axis-angle-label" x="722" y="156" text-anchor="middle">
        <tspan x="722">${t('yawLabel')} ${displayYawDegrees(state.rotation3d.yaw)}°</tspan>
        <tspan x="722" dy="16">${t('pitchLabel')} ${Math.round(state.rotation3d.pitch)}°</tspan>
      </text>`;

  return `
    <g class="orientation-axis-control" aria-label="${t('orientationAxisControl')}">
      <rect class="orientation-axis-panel" x="648" y="18" width="148" height="184" rx="16" />
      <text class="orientation-axis-heading" x="722" y="40" text-anchor="middle">${t('orientation').toLowerCase()}</text>
      ${axisMarkup}
      ${orientationStatus}
    </g>
  `;
}

function set3dOrientation(axis) {
  const preset = orientationPresets()[axis];
  if (!preset) return;
  state.rotation3d = { yaw: normalizeYaw(preset.yaw), pitch: preset.pitch };
  state.activeOrientationLabel = preset.label;
  renderResults();
}

function renderSeatEncroachmentWedge3d(zone, project) {
  const rawVertices = createSeatEncroachmentWedgeVertices(zone);
  if (rawVertices.length === 0) return [];
  const vertices = rawVertices.map(project);
  const title = t('seatWedgeTitle').replace('{angle}', String(seatBackAngleDegrees(zone)));
  return [
    renderFace(vertices, [0, 1, 2], '#fecaca', 'seat-encroachment-face', title),
    renderFace(vertices, [3, 5, 4], '#fecaca', 'seat-encroachment-face', title),
    renderFace(vertices, [1, 4, 5, 2], '#fee2e2', 'seat-encroachment-face', title),
    renderFace(vertices, [0, 3, 4, 1], '#fecaca', 'seat-encroachment-face', title),
    renderFace(vertices, [0, 2, 5, 3], '#fee2e2', 'seat-encroachment-face', title)
  ];
}

function renderSeatGuide3d(zone, project) {
  const dimensions = zone.dimensionsMm;
  const seatDepth = Math.max(90, dimensions.length * 0.12);
  const seatHeight = Math.min(Math.max(360, dimensions.height * 0.82), dimensions.height + 140);
  const seatWidth = dimensions.width * 0.28;
  const gap = dimensions.width * 0.08;
  const startY = (dimensions.width - seatWidth * 2 - gap) / 2;

  return [0, 1].flatMap((index) => {
    const vertices = createBoxVertices(
      { x: dimensions.length + seatDepth * 0.15, y: startY + index * (seatWidth + gap), z: 0 },
      { length: seatDepth, width: seatWidth, height: seatHeight }
    ).map(project);

    return [
      renderFace(vertices, [0, 1, 2, 3], '#fde68a', 'seat-face', t('seatGuideTitle')),
      renderFace(vertices, [3, 0, 4, 7], '#fef3c7', 'seat-face', t('seatGuideTitle')),
      renderFace(vertices, [4, 5, 6, 7], '#fef3c7', 'seat-face', t('seatGuideTitle'))
    ];
  });
}

function renderZone3dSvg(zone, placements) {
  const svgWidth = 820;
  const svgHeight = 440;
  const padding = 34;
  const seatGuidePoints = createSeatGuideVertices(zone);
  const seatEncroachmentWedgePoints = createSeatEncroachmentWedgeVertices(zone);
  const project = createProjector(zone, placements, svgWidth, svgHeight, padding, [...seatGuidePoints, ...seatEncroachmentWedgePoints]);
  const zoneVertices = createBoxVertices({ x: 0, y: 0, z: 0 }, zone.dimensionsMm).map(project);
  const faces = [
    ...renderSeatGuide3d(zone, project),
    ...renderSeatEncroachmentWedge3d(zone, project),
    renderFace(zoneVertices, [0, 1, 2, 3], '#dbeafe', 'zone-face zone-face--floor'),
    ...placements.flatMap((placement) => {
      const color = colorForPlacement(placement);
      const vertices = createBoxVertices(placement.positionMm, placement.orientationMm).map(project);
      const title = `${localizedPlacementLabel(placement)}: ${dimensionsLabel(placement.orientationMm)}`;
      return [
        renderFace(vertices, [0, 1, 2, 3], shadeColor(color, -18), 'bag-face', title),
        renderFace(vertices, [0, 1, 5, 4], shadeColor(color, -8), 'bag-face', title),
        renderFace(vertices, [1, 2, 6, 5], shadeColor(color, -14), 'bag-face', title),
        renderFace(vertices, [2, 3, 7, 6], shadeColor(color, 2), 'bag-face', title),
        renderFace(vertices, [3, 0, 4, 7], shadeColor(color, -22), 'bag-face', title),
        renderFace(vertices, [4, 5, 6, 7], shadeColor(color, 12), 'bag-face', title)
      ];
    })
  ].sort((a, b) => a.depth - b.depth).map((face) => face.markup).join('');

  return `
    <article class="zone-card zone-card--3d">
      <div class="zone-card__header">
        <div>
          <strong>${localizeEntity(zone, 'label')}</strong>
          <span>${dimensionsLabel(zone.dimensionsMm)} · ${zone.volumeLitres} L</span>
        </div>
        <span>${t('dragHint')}</span>
      </div>
      <svg class="zone-3d-svg" viewBox="0 0 ${svgWidth} ${svgHeight}" role="img" aria-label="${localizeEntity(zone, 'label')} ${t('zone3dAria')}">
        <rect x="0" y="0" width="${svgWidth}" height="${svgHeight}" rx="18" fill="#f8fafc" />
        ${faces}
        <polyline class="zone-wire" points="${polygonPoints([zoneVertices[0], zoneVertices[1], zoneVertices[2], zoneVertices[3], zoneVertices[0]])}" />
        <line class="zone-wire" x1="${zoneVertices[0].x}" y1="${zoneVertices[0].y}" x2="${zoneVertices[4].x}" y2="${zoneVertices[4].y}" />
        <line class="zone-wire" x1="${zoneVertices[1].x}" y1="${zoneVertices[1].y}" x2="${zoneVertices[5].x}" y2="${zoneVertices[5].y}" />
        <line class="zone-wire" x1="${zoneVertices[2].x}" y1="${zoneVertices[2].y}" x2="${zoneVertices[6].x}" y2="${zoneVertices[6].y}" />
        <line class="zone-wire" x1="${zoneVertices[3].x}" y1="${zoneVertices[3].y}" x2="${zoneVertices[7].x}" y2="${zoneVertices[7].y}" />
        <polyline class="zone-wire" points="${polygonPoints([zoneVertices[4], zoneVertices[5], zoneVertices[6], zoneVertices[7], zoneVertices[4]])}" />
        ${renderOrientationAxisControl()}
      </svg>
      ${placements.length === 0 ? `<p class="empty-zone">${t('noBagsInZone')}</p>` : ''}
    </article>
  `;
}

function renderVisualization(vehicle, config, result) {
  const zones = config.cargoZoneIds.map((id) => vehicle.cargoZones.find((zone) => zone.id === id)).filter(Boolean);
  setSanitizedMarkup(visualization, zones.map((zone, index) => {
    const placements = result.placements.filter((placement) => placement.zoneId === zone.id);
    return state.activeView === '3d' ? renderZone3dSvg(zone, placements) : renderZoneSvg(zone, placements, index);
  }).join(''));
  bind3dRotation();
}

function bind3dRotation() {
  if (state.activeView !== '3d') return;
  visualization.querySelectorAll('.zone-3d-svg').forEach((svg) => {
    svg.querySelectorAll('.orientation-axis-button').forEach((button) => {
      button.addEventListener('click', (event) => {
        event.stopPropagation();
        set3dOrientation(button.dataset.axis);
      });
      button.addEventListener('keydown', (event) => {
        if (event.key !== 'Enter' && event.key !== ' ') return;
        event.preventDefault();
        event.stopPropagation();
        set3dOrientation(button.dataset.axis);
      });
    });

    svg.addEventListener('pointerdown', (event) => {
      if (event.target.closest('.orientation-axis-control')) return;
      event.preventDefault();
      let previous = { x: event.clientX, y: event.clientY };
      svg.classList.add('is-dragging');

      const handleMove = (moveEvent) => {
        const dx = moveEvent.clientX - previous.x;
        const dy = moveEvent.clientY - previous.y;
        previous = { x: moveEvent.clientX, y: moveEvent.clientY };
        state.rotation3d.yaw = normalizeYaw(state.rotation3d.yaw - dx * 0.35);
        state.rotation3d.pitch = clamp(state.rotation3d.pitch - dy * 0.25, 0, 90);
        if (dx || dy) state.activeOrientationLabel = '';
        renderResults();
      };
      const endDrag = () => {
        window.removeEventListener('pointermove', handleMove);
        window.removeEventListener('pointerup', endDrag);
        window.removeEventListener('pointercancel', endDrag);
        visualization.querySelectorAll('.zone-3d-svg').forEach((currentSvg) => currentSvg.classList.remove('is-dragging'));
      };

      window.addEventListener('pointermove', handleMove);
      window.addEventListener('pointerup', endDrag, { once: true });
      window.addEventListener('pointercancel', endDrag, { once: true });
    });
  });
}

function renderLists(result) {
  const placedList = $('#placedList');
  if (result.placements.length) {
    placedList.replaceChildren(...result.placements.map((placement) => {
      const sourceId = placement.sourceId ?? placement.itemId.split('#')[0];
      const tint = colorForSourceId(sourceId);
      const li = createEl('li', { className: 'placed-item', attrs: { 'data-source-id': sourceId } });
      li.append(
        createEl('span', { className: 'item-status item-status--placed', text: '✓', attrs: { 'aria-hidden': 'true' } }),
        createEl('button', { className: 'placed-delete', text: '✕', attrs: { type: 'button', title: t('removeOne').replace('{item}', localizedPlacementLabel(placement)), 'aria-label': t('removeOne').replace('{item}', localizedPlacementLabel(placement)) } }),
        createEl('strong', { text: localizedPlacementLabel(placement) }),
        createEl('small', { text: `${localizedZoneLabel(placement.zoneLabel, placement.zoneId)} · ${dimensionsLabel(placement.orientationMm)}` })
      );
      li.style.setProperty('--bag-panel-bg', mixWithWhite(tint, 0.9));
      return li;
    }));
  } else {
    placedList.replaceChildren(createEl('li', { className: 'muted', text: t('nothingPlacedYet') }));
  }

  const unplacedList = $('#unplacedList');
  if (result.unplacedItems.length) {
    unplacedList.replaceChildren(...result.unplacedItems.map((item) => {
      const sourceId = item.sourceId ?? item.id?.split('#')[0] ?? item.id;
      const tint = colorForSourceId(sourceId);
      const li = createEl('li', { className: 'problem placed-item', attrs: { 'data-source-id': sourceId } });
      li.append(
        createEl('span', { className: 'item-status item-status--unplaced', text: '⊘', attrs: { 'aria-hidden': 'true' } }),
        createEl('button', { className: 'placed-delete', text: '✕', attrs: { type: 'button', title: t('removeOne').replace('{item}', localizedPlacementLabel(item)), 'aria-label': t('removeOne').replace('{item}', localizedPlacementLabel(item)) } }),
        createEl('strong', { text: localizedPlacementLabel(item) }),
        createEl('small', { text: `${dimensionsLabel(item.dimensionsMm)} · ${item.volumeLitres} L` })
      );
      li.style.setProperty('--bag-panel-bg', mixWithWhite(tint, 0.9));
      return li;
    }));
  } else {
    unplacedList.replaceChildren(createEl('li', { className: 'success', text: t('allPlaced') }));
  }
}

function renderResults() {
  const vehicle = selectedVehicle();
  const config = selectedConfiguration(vehicle);
  const zones = config.cargoZoneIds.map((id) => vehicle.cargoZones.find((zone) => zone.id === id)).filter(Boolean);
  const luggageSet = cloneLuggageWithQuantities();
  const result = estimateFit(luggageSet, vehicle, config.id, {
    considerSeatBackEncroachment: hasActiveSeatBackEncroachment(zones),
    seatBackAngleDegrees: state.seatBackEncroachmentAngleDegrees,
    defaultUsableFraction: (100 - state.usableVolumeBufferPercent) / 100
  });
  const percent = Math.round(result.fitScore * 100);
  const volumePercent = Math.round((result.usedVolumeLitres / Math.max(1, result.usableVolumeLitres)) * 100);

  const fitResultLabel = t('placedCount').replace('{placed}', String(result.placements.length)).replace('{unplaced}', String(result.unplacedItems.length));
  const fitResultDetail = t('volumeUsedPercent').replace('{percent}', String(volumePercent));

  $('#resultTitle').textContent = `${vehicle.make} ${vehicle.model} · ${localizeEntity(config, 'label')}`;
  $('#fitBadge').className = `fit-badge ${result.fits ? 'fit-badge--ok' : 'fit-badge--bad'}`;
  $('#fitBadge').textContent = result.fits ? t('bagsFit') : t('bagsUnplaced');
  $('#metrics').replaceChildren(...[
    metricCard(t('fitScore'), `${percent}%`, t('placedSummary').replace('{placed}', String(result.placements.length)).replace('{total}', String(result.placements.length + result.unplacedItems.length))),
    metricCard(t('usableVolume'), `${result.usableVolumeLitres} L`, t('usedVolume').replace('{used}', String(result.usedVolumeLitres))),
    metricCard(t('fitResult'), fitResultLabel, fitResultDetail, 'metric--fit-result')
  ]);
  renderVisualization(vehicle, config, result);
  renderLists(result);
  syncCustomBagControlState(result);
  $('#warnings').replaceChildren();
}

function bindEvents() {
  vehicleSelect.addEventListener('change', () => {
    state.vehicleId = vehicleSelect.value;
    renderConfigurationOptions();
    syncSeatBackEncroachmentDefault();
    state.usableVolumeBufferPercent = DEFAULT_USABLE_VOLUME_BUFFER_PERCENT;
    state.usableVolumeBufferInputPercent = String(DEFAULT_USABLE_VOLUME_BUFFER_PERCENT);
    renderSeatBackEncroachmentState();
    persistTripSetupPreference();
    renderResults();
  });
  configurationSelect.addEventListener('change', () => {
    state.configurationId = configurationSelect.value;
    syncSeatBackEncroachmentDefault();
    renderSeatBackEncroachmentState();
    persistTripSetupPreference();
    renderResults();
  });
  const updateBoundaryStatus = (input, isOutOfBounds) => {
    input.classList.toggle('field-input--out-of-bounds', isOutOfBounds);
    input.setAttribute('aria-invalid', isOutOfBounds ? 'true' : 'false');
  };

  seatBackEncroachmentDegreesInput.addEventListener('input', () => {
    state.seatBackEncroachmentInputDegrees = seatBackEncroachmentDegreesInput.value;
    const parsed = Number.parseInt(state.seatBackEncroachmentInputDegrees, 10);
    const hasValue = Number.isFinite(parsed);
    const isOutOfBounds = hasValue && (parsed < 0 || parsed > MAX_SEAT_BACK_ANGLE_DEGREES);
    updateBoundaryStatus(seatBackEncroachmentDegreesInput, isOutOfBounds);
    state.seatBackEncroachmentAngleDegrees = hasValue
      ? clamp(parsed, 0, MAX_SEAT_BACK_ANGLE_DEGREES)
      : DEFAULT_SEAT_BACK_ANGLE_DEGREES;
    persistTripSetupPreference();
    renderResults();
  });

  const updateUsableVolumeBuffer = () => {
    state.usableVolumeBufferInputPercent = usableVolumeBufferPercentInput.value;
    const parsed = Number.parseInt(state.usableVolumeBufferInputPercent, 10);
    const hasValue = Number.isFinite(parsed);
    const isOutOfBounds = hasValue && (parsed < MIN_USABLE_VOLUME_BUFFER_PERCENT || parsed > MAX_USABLE_VOLUME_BUFFER_PERCENT);
    updateBoundaryStatus(usableVolumeBufferPercentInput, isOutOfBounds);
    state.usableVolumeBufferPercent = hasValue
      ? clamp(parsed, MIN_USABLE_VOLUME_BUFFER_PERCENT, MAX_USABLE_VOLUME_BUFFER_PERCENT)
      : DEFAULT_USABLE_VOLUME_BUFFER_PERCENT;
    persistTripSetupPreference();
    renderResults();
  };

  usableVolumeBufferPercentInput.addEventListener('input', updateUsableVolumeBuffer);
  usableVolumeBufferPercentInput.addEventListener('change', updateUsableVolumeBuffer);
  usableVolumeBufferPercentInput.addEventListener('blur', updateUsableVolumeBuffer);
  resetLuggageButton.addEventListener('click', resetLuggageQuantities);
  document.querySelectorAll('.view-tab').forEach((button) => button.addEventListener('click', () => {
    state.activeView = button.dataset.view;
    document.querySelectorAll('.view-tab').forEach((tab) => tab.classList.toggle('active', tab === button));
    renderResults();
  }));
  $('#placedList').addEventListener('click', (event) => {
    const deleteButton = event.target.closest('.placed-delete');
    if (!deleteButton) return;
    const row = deleteButton.closest('.placed-item');
    const sourceId = row?.dataset.sourceId;
    if (!sourceId) return;
    const quantityInput = $(`#qty-${sourceId}`);
    if (!quantityInput) return;
    const current = Math.max(0, Number(quantityInput.value) || 0);
    quantityInput.value = String(Math.max(0, current - 1));
    renderResults();
  });
  $('#unplacedList').addEventListener('click', (event) => {
    const deleteButton = event.target.closest('.placed-delete');
    if (!deleteButton) return;
    const row = deleteButton.closest('.placed-item');
    const sourceId = row?.dataset.sourceId;
    if (!sourceId) return;
    const quantityInput = $(`#qty-${sourceId}`);
    if (!quantityInput) return;
    const current = Math.max(0, Number(quantityInput.value) || 0);
    quantityInput.value = String(Math.max(0, current - 1));
    renderResults();
  });
  $('#languageSelect').addEventListener('change', (event) => {
    setLanguage(event.target.value);
  });
}

function applyStaticTranslations() {
  document.title = t('pageTitle');
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const key = el.dataset.i18n;
    el.textContent = t(key);
  });
  document.querySelectorAll('[data-i18n-aria-label]').forEach((el) => {
    const key = el.dataset.i18nAriaLabel;
    el.setAttribute('aria-label', t(key));
  });
}

function setLanguage(language) {
  state.language = language;
  document.documentElement.lang = language;
  const languageSelect = $('#languageSelect');
  if (languageSelect && languageSelect.value !== language) {
    languageSelect.value = language;
  }
  persistLanguagePreference(language);
  applyStaticTranslations();
  renderVehicleOptions();
  renderConfigurationOptions();
  renderSeatBackEncroachmentState();
  renderLuggageControls();
  renderResults();
}

function currentVehicleDefaults(vehicle = selectedVehicle()) {
  const defaultConfigurationId = vehicle.seatConfigurations[0]?.id ?? '';
  const defaultBufferPercent = DEFAULT_USABLE_VOLUME_BUFFER_PERCENT;
  const zones = (vehicle.seatConfigurations[0]?.cargoZoneIds ?? [])
    .map((id) => vehicle.cargoZones.find((zone) => zone.id === id))
    .filter(Boolean);
  return {
    configurationId: defaultConfigurationId,
    seatBackAngleDegrees: defaultSeatBackAngleDegrees(zones),
    usableVolumeBufferPercent: defaultBufferPercent
  };
}

function persistTripSetupPreference() {
  persistTripSetupPreferenceState({ selectedVehicle, currentVehicleDefaults, state });
}

function persistLanguagePreference(language) {
  persistLanguagePreferenceState({ language, defaultLanguage: DEFAULT_LANGUAGE, clearCookieFn: clearCookie, setCookieFn: setCookie });
}

function applyPersistedTripSetupPreference() {
  const raw = cookieValue(TRIP_SETUP_COOKIE_NAME);
  if (!raw) return;
  try {
    const persisted = JSON.parse(raw);
    if (!persisted || typeof persisted !== 'object') return;
    const persistedVehicle = state.vehicles.find((vehicle) => vehicle.id === persisted.vehicleId);
    if (!persistedVehicle) return;
    state.vehicleId = persistedVehicle.id;
    const vehicle = selectedVehicle();
    const defaults = currentVehicleDefaults(vehicle);
    const validConfig = vehicle.seatConfigurations.some((config) => config.id === persisted.configurationId);
    state.configurationId = validConfig ? persisted.configurationId : defaults.configurationId;
    state.seatBackEncroachmentAngleDegrees = typeof persisted.seatBackAngleDegrees === 'number'
      ? clamp(persisted.seatBackAngleDegrees, 0, MAX_SEAT_BACK_ANGLE_DEGREES)
      : defaults.seatBackAngleDegrees;
    state.usableVolumeBufferPercent = typeof persisted.usableVolumeBufferPercent === 'number'
      ? clamp(persisted.usableVolumeBufferPercent, MIN_USABLE_VOLUME_BUFFER_PERCENT, MAX_USABLE_VOLUME_BUFFER_PERCENT)
      : defaults.usableVolumeBufferPercent;
  } catch {
    clearCookie(TRIP_SETUP_COOKIE_NAME);
  }
}

async function renderBuildVersion() {
  const appVersionEl = $('#appVersion');
  if (!appVersionEl) return;
  try {
    const version = await readJson('./version.json');
    if (!version?.displayVersion || !version?.fullSha) return;
    appVersionEl.innerHTML = '';
    const label = document.createElement('span');
    label.textContent = 'Version: ';
    const link = document.createElement('a');
    link.href = version.githubCommitUrl || '#';
    link.textContent = version.displayVersion;
    link.target = '_blank';
    link.rel = 'noopener noreferrer';
    link.title = version.fullSha;
    appVersionEl.append(label, link);
  } catch (error) {
    console.warn('Unable to load version metadata', error);
  }
}

export async function initApp() {
  try {
    const [luggageSet, vehicles] = await Promise.all([
      readJson('./configs/luggage/common.json'),
      loadVehicles()
    ]);
    state.luggageSet = luggageSet;
    state.vehicles = vehicles.sort((a, b) => vehicleLabel(a).localeCompare(vehicleLabel(b)));
    const initialVehicle = defaultVehicle();
    state.vehicleId = initialVehicle.id;
    state.configurationId = initialVehicle.seatConfigurations[0].id;
    syncSeatBackEncroachmentDefault();
    applyPersistedTripSetupPreference();
    renderVehicleOptions();
    renderConfigurationOptions();
    renderSeatBackEncroachmentState();
    renderLuggageControls();
    await renderBuildVersion();
    bindEvents();
    const persistedLanguage = getPersistedLanguagePreference();
    if (persistedLanguage && persistedLanguage !== state.language) {
      setLanguage(persistedLanguage);
      return;
    }
    applyStaticTranslations();
    renderSeatBackEncroachmentState();
    renderResults();
  } catch (error) {
    $('#metrics').replaceChildren(metricCard(t('fitResult'), t('loadErrorTitle'), error.message, 'metric--fit-result'));
    console.error(error);
  }
}

if (typeof window !== 'undefined' && typeof document !== 'undefined') {
  initApp().catch((error) => {
    console.error('Failed to initialize app', error);
  });
}
