import { estimateFit } from '../fitEstimator.js';
import { I18N } from '../configs/i18n/index.js';
import {
  isValidCustomBagDimensions,
  validatePersistedTripSetupPayload,
  validateSeatBackAngleInput,
  validateUsableVolumeBufferInput
} from '../src/state/validators.js';
import { createLocalization } from '../src/i18n/localization.js';
import { createControlsStateSync } from '../src/render/controlsState.js';
import { createListsRenderer } from '../src/render/lists.js';
import { createMetricsHeaderRenderer } from '../src/render/metricsHeader.js';
import {
  clamp,
  createBoxVertices,
  createProjector,
  createSeatGuideVertices,
  dimensionsLabel,
  displayYawDegrees,
  mixWithWhite,
  normalizeYaw,
  polygonPoints,
  projectBox,
  projectZone,
  renderFace,
  rotatePoint3d,
  shadeColor
} from '../src/render/helpers.js';
import { createVisualizationRenderer } from '../src/render/visualization.js';
import { createPersistence } from '../persistence.js';
import { createActions } from '../src/events/actions.js';
import { createEventBindings } from '../src/events/bindings.js';

const VEHICLE_INDEX_PATH = './configs/vehicles/index.json';

const BAG_COLORS = ['#2563eb', '#16a34a', '#f97316', '#9333ea', '#0891b2', '#e11d48', '#ca8a04', '#4f46e5'];
const CUSTOM_BAG_COLOR = '#facc15';
const DEFAULT_SEAT_BACK_ANGLE_DEGREES = 20;
const MAX_SEAT_BACK_ANGLE_DEGREES = 45;
const DEFAULT_USABLE_VOLUME_BUFFER_PERCENT = 10;
const MIN_USABLE_VOLUME_BUFFER_PERCENT = 5;
const MAX_USABLE_VOLUME_BUFFER_PERCENT = 50;
const DEFAULT_MAX_QUANTITY_BY_SIZE = {
  large: 12,
  medium: 24,
  small: 36,
  verySmall: 50
};
const CUSTOM_BAG_ID = 'custom-bag';
const CUSTOM_BAG_MIN_DIMENSIONS_MM = { length: 10, width: 10, height: 10 };
const CUSTOM_BAG_MAX_DIMENSIONS_MM = { length: 2500, width: 2500, height: 2500 };
const state = {
  luggageSet: null,
  vehicles: [],
  vehicleId: '',
  configurationId: '',
  activeView: '3d',
  seatBackEncroachmentAngleDegrees: DEFAULT_SEAT_BACK_ANGLE_DEGREES,
  seatBackEncroachmentInputDegrees: String(DEFAULT_SEAT_BACK_ANGLE_DEGREES),
  usableVolumeBufferPercent: DEFAULT_USABLE_VOLUME_BUFFER_PERCENT,
  usableVolumeBufferInputPercent: String(DEFAULT_USABLE_VOLUME_BUFFER_PERCENT),
  rotation3d: { yaw: 315, pitch: 60 },
  activeOrientationLabel: '',
  language: 'en'
};

const LANGUAGE_COOKIE_NAME = 'preferredLanguage';
const LANGUAGE_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 365;
const DEFAULT_LANGUAGE = 'en';
const TRIP_SETUP_COOKIE_NAME = 'tripSetup';
const { localeBundle, t, localizeEntity } = createLocalization({ state, i18n: I18N });

const $ = (selector) => document.querySelector(selector);
function createEl(tag, { className = '', text = '', attrs = {} } = {}) {
  const el = document.createElement(tag);
  if (className) el.className = className;
  if (text !== '') el.textContent = text;
  Object.entries(attrs).forEach(([key, value]) => el.setAttribute(key, String(value)));
  return el;
}
function setSanitizedMarkup(element, markup) {
  // Markup rendered here is generated by local application code (not user-entered HTML).
  // Keep the assignment isolated in one utility to make future sanitizer swaps easy.
  element.innerHTML = markup;
}
const vehicleSelect = $('#vehicleSelect');
const configurationSelect = $('#configurationSelect');
const seatBackEncroachmentDegreesInput = $('#seatBackEncroachmentDegrees');
const seatBackEncroachmentNote = $('#seatBackEncroachmentNote');
const usableVolumeBufferPercentInput = $('#usableVolumeBufferPercent');
const usableVolumeBufferNote = $('#usableVolumeBufferNote');
const luggageControls = $('#luggageControls');
const resetLuggageButton = $('#resetLuggageButton');
const visualization = $('#visualization');
const languageSelect = $('#languageSelect');
const placedList = $('#placedList');
const unplacedList = $('#unplacedList');

function updateBoundaryStatus(input, isOutOfBounds) {
  input.classList.toggle('field-input--out-of-bounds', isOutOfBounds);
  input.setAttribute('aria-invalid', isOutOfBounds ? 'true' : 'false');
}

async function readJson(path) {
  const response = await fetch(path);
  if (!response.ok) throw new Error(`Unable to load ${path}`);
  return response.json();
}

async function loadVehicles() {
  const vehicleIndex = await readJson(VEHICLE_INDEX_PATH);
  return Promise.all(vehicleIndex.files.map((file) => readJson(`./configs/vehicles/${file}`)));
}

function defaultMaxQuantity(item) {
  const volumeMm3 = item.dimensionsMm.length * item.dimensionsMm.width * item.dimensionsMm.height;
  if (volumeMm3 >= 60_000_000) return DEFAULT_MAX_QUANTITY_BY_SIZE.large;
  if (volumeMm3 >= 20_000_000) return DEFAULT_MAX_QUANTITY_BY_SIZE.medium;
  if (volumeMm3 >= 3_000_000) return DEFAULT_MAX_QUANTITY_BY_SIZE.small;
  return DEFAULT_MAX_QUANTITY_BY_SIZE.verySmall;
}

function maxQuantityForItem(item) {
  return Math.max(1, Number(item.maxQuantity) || defaultMaxQuantity(item));
}

function hasValidCustomBagDimensions(dimensions) {
  return isValidCustomBagDimensions(dimensions, {
    min: CUSTOM_BAG_MIN_DIMENSIONS_MM,
    max: CUSTOM_BAG_MAX_DIMENSIONS_MM
  });
}

function defaultSeatBackAngleDegrees(zones) {
  return zones.find((zone) => zone.seatBackEncroachment)?.seatBackEncroachment?.angleFromVerticalDegrees ?? 0;
}

function seatBackAngleDegrees(zone) {
  const requested = zone.seatBackEncroachment ? state.seatBackEncroachmentAngleDegrees : (zone.seatBackEncroachment?.angleFromVerticalDegrees ?? DEFAULT_SEAT_BACK_ANGLE_DEGREES);
  return clamp(requested, 0, MAX_SEAT_BACK_ANGLE_DEGREES);
}

function seatBackEncroachmentMmAtHeight(zone, heightMm) {
  return heightMm * Math.tan(seatBackAngleDegrees(zone) * (Math.PI / 180));
}

function hasActiveSeatBackEncroachment(zones) {
  return zones.some((zone) => zone.seatBackEncroachment);
}

function vehicleLabel(vehicle) {
  const make = localizeEntity(vehicle, 'make');
  const model = localizeEntity(vehicle, 'model');
  const bodyStyle = localizeEntity(vehicle, 'bodyStyle');
  return `${make} ${model} (${bodyStyle})`;
}

function cloneLuggageWithQuantities() {
  return {
    ...state.luggageSet,
    items: state.luggageSet.items.map((item) => {
      const requestedQuantity = Math.min(maxQuantityForItem(item), Math.max(0, Number($(`#qty-${item.id}`).value)));
      const quantity = item.id === CUSTOM_BAG_ID && !hasValidCustomBagDimensions(item.dimensionsMm) ? 0 : requestedQuantity;
      return { ...item, quantity };
    }).filter((item) => item.quantity > 0)
  };
}

function defaultVehicle() {
  return state.vehicles.find((vehicle) => vehicle.isDefault) ?? state.vehicles[0];
}

function selectedVehicle() {
  return state.vehicles.find((vehicle) => vehicle.id === state.vehicleId) ?? defaultVehicle();
}

function selectedConfiguration(vehicle = selectedVehicle()) {
  return vehicle.seatConfigurations.find((config) => config.id === state.configurationId) ?? vehicle.seatConfigurations[0];
}

function renderVehicleOptions() {
  vehicleSelect.replaceChildren(...state.vehicles.map((vehicle) => createEl('option', {
    text: vehicleLabel(vehicle),
    attrs: { value: vehicle.id }
  })));
  vehicleSelect.value = state.vehicleId;
}

function renderConfigurationOptions() {
  const vehicle = selectedVehicle();
  configurationSelect.replaceChildren(...vehicle.seatConfigurations.map((config) => createEl('option', {
    text: `${localizeEntity(config, 'label')} · ${config.seatsAvailable} ${t('seats')}`,
    attrs: { value: config.id }
  })));
  configurationSelect.value = selectedConfiguration(vehicle).id;
}

function renderBufferControl() {
  usableVolumeBufferPercentInput.value = state.usableVolumeBufferInputPercent;
  usableVolumeBufferNote.textContent = `${t('safetyMarginNote')} (min 5%, max 50%)`;
  const { outOfBounds } = validateUsableVolumeBufferInput(state.usableVolumeBufferInputPercent, {
    min: MIN_USABLE_VOLUME_BUFFER_PERCENT,
    max: MAX_USABLE_VOLUME_BUFFER_PERCENT,
    defaultValue: DEFAULT_USABLE_VOLUME_BUFFER_PERCENT
  });
  usableVolumeBufferPercentInput.classList.toggle('field-input--out-of-bounds', outOfBounds);
}

function renderSeatBackEncroachmentState() {
  const vehicle = selectedVehicle();
  const config = selectedConfiguration(vehicle);
  const zones = config.cargoZoneIds.map((id) => vehicle.cargoZones.find((zone) => zone.id === id)).filter(Boolean);
  renderSeatBackEncroachmentControl(zones);
  renderBufferControl();
}

function renderSeatBackEncroachmentControl(zones) {
  const hasEncroachment = hasActiveSeatBackEncroachment(zones);
  seatBackEncroachmentDegreesInput.value = state.seatBackEncroachmentInputDegrees;
  seatBackEncroachmentDegreesInput.disabled = !hasEncroachment;
  seatBackEncroachmentNote.textContent = `${t('seatBackNote')} (max ${MAX_SEAT_BACK_ANGLE_DEGREES}°)`;
  const { outOfBounds } = validateSeatBackAngleInput(state.seatBackEncroachmentInputDegrees, {
    defaultValue: DEFAULT_SEAT_BACK_ANGLE_DEGREES,
    max: MAX_SEAT_BACK_ANGLE_DEGREES
  });
  seatBackEncroachmentDegreesInput.classList.toggle('field-input--out-of-bounds', outOfBounds);
}

function defaultSeatBackAngleForSelection() {
  const vehicle = selectedVehicle();
  const config = selectedConfiguration(vehicle);
  const zones = config.cargoZoneIds.map((id) => vehicle.cargoZones.find((zone) => zone.id === id)).filter(Boolean);
  const hasEncroachment = hasActiveSeatBackEncroachment(zones);
  return hasEncroachment ? defaultSeatBackAngleDegrees(zones) : 0;
}

function renderLuggageControls() {
  const quantitiesByItemId = new Map(
    state.luggageSet.items.map((item) => {
      const input = $(`#qty-${item.id}`);
      const value = input ? Number(input.value) : item.quantity;
      return [item.id, Number.isFinite(value) ? Math.max(0, value) : 0];
    })
  );
  const controls = state.luggageSet.items.map((item) => {
    const color = colorForSourceId(item.id);
    const article = createEl('article', { className: 'luggage-item', attrs: { style: `--bag-tint:${color};--bag-panel-bg:${mixWithWhite(color, 0.9)}` } });
    const meta = createEl('div');
    meta.append(createEl('strong', { text: localizeEntity(item, 'label') }));
    const dimensionsAndTypeLabel = `${dimensionsLabel(item.dimensionsMm)} · ${item.shapeType.replace('_', ' ')}`;
    if (item.id !== CUSTOM_BAG_ID) {
      meta.append(createEl('span', { text: dimensionsAndTypeLabel }));
    }
    const label = createEl('label');
    label.append(
      createEl('span', { className: 'sr-only', text: t('quantityFor').replace('{item}', localizeEntity(item, 'label')) }),
      createEl('input', { attrs: { id: `qty-${item.id}`, type: 'number', min: '0', max: String(maxQuantityForItem(item)), step: '1', value: quantitiesByItemId.get(item.id) ?? 0 } })
    );
    article.append(meta, label);
    if (item.id === CUSTOM_BAG_ID) {
      const dims = ['height', 'width', 'length'].map((axis) => {
        const input = createEl('input', {
          attrs: {
            id: `custom-${axis}`,
            type: 'number',
            min: String(CUSTOM_BAG_MIN_DIMENSIONS_MM[axis]),
            max: String(CUSTOM_BAG_MAX_DIMENSIONS_MM[axis]),
            step: '1',
            value: String(Math.round(item.dimensionsMm[axis]))
          }
        });
        const row = createEl('label', { className: 'custom-bag-dimension' });
        row.append(createEl('span', { text: `${axis === 'height' ? 'H' : axis === 'width' ? 'W' : 'D'} (mm)` }), input);
        return row;
      });
      const customDimensions = createEl('div', { className: 'custom-bag-dimensions' });
      customDimensions.append(...dims);
      meta.append(customDimensions);
    }
    return article;
  });
  luggageControls.replaceChildren(...controls);
  syncCustomBagControlState();
}

const syncCustomBagControlState = createControlsStateSync({
  state,
  $,
  customBagId: CUSTOM_BAG_ID,
  customBagMinDimensionsMm: CUSTOM_BAG_MIN_DIMENSIONS_MM,
  customBagMaxDimensionsMm: CUSTOM_BAG_MAX_DIMENSIONS_MM,
  hasValidCustomBagDimensions,
  maxQuantityForItem
});

function colorForSourceId(sourceId) {
  if (sourceId === CUSTOM_BAG_ID) return CUSTOM_BAG_COLOR;
  const uniqueSources = [...new Set(estimateSources().map((item) => item.id))];
  const index = uniqueSources.indexOf(sourceId);
  return BAG_COLORS[(index < 0 ? 0 : index) % BAG_COLORS.length];
}

function colorForPlacement(placement) {
  const source = placement.sourceId ?? placement.itemId.split('#')[0];
  return colorForSourceId(source);
}


function localizedPlacementLabel(entry) {
  const sourceId = entry.sourceId ?? (entry.itemId ? entry.itemId.split('#')[0] : null);
  const item = state.luggageSet?.items?.find((candidate) => candidate.id === sourceId);
  if (item) return localizeEntity(item, 'label');
  if (entry?.label) {
    const directLabel = localizeEntity(entry, 'label');
    if (directLabel !== 'label') return directLabel;
  }
  return entry.label ?? sourceId ?? '';
}

function localizedZoneLabel(label, zoneId) {
  const vehicle = selectedVehicle();
  const zone = vehicle?.cargoZones?.find((candidate) => candidate.id === zoneId);
  if (!zone) return label;
  return localizeEntity(zone, 'label');
}

function estimateSources() {
  return state.luggageSet?.items ?? [];
}

function seatEncroachmentOverlay(zone, projection, view, padding, scale) {
  if (view !== 'side' || !hasActiveSeatBackEncroachment([zone]) || !zone.dimensionsMm) return '';

  const floorX = padding + projection.width * scale;
  const topX = padding + Math.max(0, projection.width - seatBackEncroachmentMmAtHeight(zone, zone.dimensionsMm.height)) * scale;
  const floorY = padding + projection.height * scale;
  const topY = padding;
  return `
    <g aria-label="${t('seatEncroachmentEnvelope')}">
      <polygon class="seat-encroachment-area" points="${floorX},${floorY} ${floorX},${topY} ${topX},${topY}" />
      <line class="seat-encroachment-line" x1="${floorX}" y1="${floorY}" x2="${topX}" y2="${topY}" />
    </g>
  `;
}

function seatOutlineFor2dView(projection, view, padding, scale) {
  const seatFill = '#fef3c7';
  const seatStroke = '#92400e';
  const label = t('forwardSeats');

  if (view === 'side') {
    const x = padding + projection.width * scale + 14;
    const floorY = padding + projection.height * scale;
    const seatWidth = Math.min(58, projection.width * scale * 0.18);
    const seatHeight = Math.min(92, projection.height * scale * 0.7);
    const baseHeight = Math.max(12, seatHeight * 0.28);
    return `
      <g class="seat-outline seat-outline--side" aria-label="${label}">
        <path d="M ${x} ${floorY - baseHeight} h ${seatWidth} q 8 0 8 8 v ${baseHeight - 8} h ${-seatWidth - 8} z" fill="${seatFill}" stroke="${seatStroke}" />
        <path d="M ${x + seatWidth * 0.46} ${floorY - baseHeight} l ${seatWidth * 0.18} ${-seatHeight} q 3 -10 14 -7 l ${seatWidth * 0.18} 4 l ${-seatWidth * 0.23} ${seatHeight + 3} z" fill="${seatFill}" stroke="${seatStroke}" />
        <text x="${x + seatWidth / 2}" y="${Math.max(18, floorY - seatHeight - 14)}" text-anchor="middle" class="seat-label">${t('front')}</text>
      </g>
    `;
  }

  if (view === 'front') {
    const cargoX = padding;
    const cargoY = padding;
    const cargoWidth = projection.width * scale;
    const seatWidth = Math.max(42, cargoWidth * 0.26);
    const seatHeight = Math.min(54, projection.height * scale * 0.28);
    const gap = Math.max(14, cargoWidth * 0.08);
    const startX = cargoX + (cargoWidth - seatWidth * 2 - gap) / 2;
    const y = Math.max(8, cargoY - seatHeight - 8);
    return `
      <g class="seat-outline seat-outline--front" aria-label="${label}">
        <rect x="${startX}" y="${y}" width="${seatWidth}" height="${seatHeight}" rx="11" fill="${seatFill}" stroke="${seatStroke}" />
        <rect x="${startX + seatWidth + gap}" y="${y}" width="${seatWidth}" height="${seatHeight}" rx="11" fill="${seatFill}" stroke="${seatStroke}" />
        <text x="${cargoX + cargoWidth / 2}" y="${Math.max(14, y - 6)}" text-anchor="middle" class="seat-label">${t('front')}</text>
      </g>
    `;
  }

  const cargoX = padding;
  const cargoY = padding;
  const cargoWidth = projection.width * scale;
  const cargoHeight = projection.height * scale;
  const seatDepth = Math.min(76, cargoWidth * 0.18);
  const seatWidth = Math.max(44, cargoHeight * 0.28);
  const gap = Math.max(12, cargoHeight * 0.08);
  const startY = cargoY + (cargoHeight - seatWidth * 2 - gap) / 2;
  const x = cargoX + cargoWidth + 14;
  return `
    <g class="seat-outline seat-outline--top" aria-label="${label}">
      <rect x="${x}" y="${startY}" width="${seatDepth}" height="${seatWidth}" rx="12" fill="${seatFill}" stroke="${seatStroke}" />
      <rect x="${x}" y="${startY + seatWidth + gap}" width="${seatDepth}" height="${seatWidth}" rx="12" fill="${seatFill}" stroke="${seatStroke}" />
      <line x1="${cargoX + cargoWidth}" y1="${cargoY}" x2="${cargoX + cargoWidth}" y2="${cargoY + cargoHeight}" class="seat-back-line" />
      <text x="${x + seatDepth / 2}" y="${Math.max(18, startY - 8)}" text-anchor="middle" class="seat-label">${t('front')}</text>
    </g>
  `;
}

function renderZoneSvg(zone, placements, index) {
  const projection = projectZone(zone, state.activeView, t);
  const padding = state.activeView === 'front' ? 82 : 28;
  const seatGutter = state.activeView === 'front' ? 0 : 112;
  const maxSvgWidth = 720;
  const contentWidth = maxSvgWidth - padding * 2 - seatGutter;
  const scale = Math.min(contentWidth / projection.width, 320 / projection.height);
  const svgWidth = Math.max(360, projection.width * scale + padding * 2 + seatGutter);
  const svgHeight = Math.max(220, projection.height * scale + padding * 2 + 34);
  const seatOutline = seatOutlineFor2dView(projection, state.activeView, padding, scale);
  const encroachmentOverlay = seatEncroachmentOverlay(zone, projection, state.activeView, padding, scale);

  const rects = placements.map((placement) => {
    const box = projectBox(placement, state.activeView);
    const x = padding + box.x * scale;
    const y = padding + (projection.height - box.y - box.height) * scale;
    const width = Math.max(4, box.width * scale);
    const height = Math.max(4, box.height * scale);
    return `
      <g>
        <rect class="luggage-rect" x="${x}" y="${y}" width="${width}" height="${height}" rx="7" fill="${colorForPlacement(placement)}" />
        <title>${localizedPlacementLabel(placement)}: ${dimensionsLabel(placement.orientationMm)}</title>
      </g>
    `;
  }).join('');

  return `
    <article class="zone-card">
      <div class="zone-card__header">
        <strong>${localizeEntity(zone, 'label')}</strong>
        <span>${dimensionsLabel(zone.dimensionsMm)} · ${zone.volumeLitres} L</span>
      </div>
      <svg viewBox="0 0 ${svgWidth} ${svgHeight}" role="img" aria-label="${t('zoneViewAria').replace('{zone}', localizeEntity(zone, 'label')).replace('{view}', state.activeView)}">
        ${seatOutline}
        <rect class="cargo-outline" x="${padding}" y="${padding}" width="${projection.width * scale}" height="${projection.height * scale}" rx="12" fill="#eff6ff" />
        ${encroachmentOverlay}
        ${rects}
        <text x="${padding}" y="${svgHeight - 12}" class="axis-label">${projection.xLabel}: ${projection.width} mm</text>
        <text x="${svgWidth - padding}" y="${svgHeight - 12}" text-anchor="end" class="axis-label">${projection.yLabel}: ${projection.height} mm</text>
      </svg>
      ${placements.length === 0 ? `<p class="empty-zone">${t('noBagsInZone')}</p>` : ''}
    </article>
  `;
}


function createSeatEncroachmentWedgeVertices(zone) {
  if (!hasActiveSeatBackEncroachment([zone]) || !zone.dimensionsMm) return [];
  const dimensions = zone.dimensionsMm;
  const topEncroachment = clamp(seatBackEncroachmentMmAtHeight(zone, dimensions.height), 0, dimensions.length);
  const topX = dimensions.length - topEncroachment;
  return [
    { x: dimensions.length, y: 0, z: 0 },
    { x: dimensions.length, y: 0, z: dimensions.height },
    { x: topX, y: 0, z: dimensions.height },
    { x: dimensions.length, y: dimensions.width, z: 0 },
    { x: dimensions.length, y: dimensions.width, z: dimensions.height },
    { x: topX, y: dimensions.width, z: dimensions.height }
  ];
}

function current3dAngles() {
  return {
    yaw: normalizeYaw(state.rotation3d.yaw) * Math.PI / 180,
    pitch: state.rotation3d.pitch * Math.PI / 180
  };
}

function orientationPresets() {
  return {
    x: { label: t('bootView'), yaw: 270, pitch: 90 },
    y: { label: t('sideView'), yaw: 0, pitch: 90 },
    z: { label: t('topView'), yaw: -90, pitch: 0 }
  };
}

function renderOrientationAxisControl() {
  const origin = { x: 710, y: 104 };
  const axisLength = 44;
  const center = { x: 0, y: 0, z: 0 };
  const axes = [
    { key: 'x', label: 'X', color: '#dc2626', vector: { x: axisLength, y: 0, z: 0 }, title: t('bootView') },
    { key: 'y', label: 'Y', color: '#16a34a', vector: { x: 0, y: axisLength, z: 0 }, title: t('sideView') },
    { key: 'z', label: 'Z', color: '#2563eb', vector: { x: 0, y: 0, z: axisLength }, title: t('topView') }
  ];

  const axisMarkup = axes.map((axis) => {
    const endpoint = rotatePoint3d(axis.vector, center, current3dAngles());
    const x = origin.x + endpoint.x;
    const y = origin.y + endpoint.y;
    const labelX = origin.x + endpoint.x * 1.18;
    const labelY = origin.y + endpoint.y * 1.18;

    return `
      <g class="orientation-axis-button" role="button" tabindex="0" data-axis="${axis.key}" aria-label="${t('switchTo').replace('{view}', axis.title)}" style="--axis-color:${axis.color}">
        <line class="orientation-axis-line" x1="${origin.x}" y1="${origin.y}" x2="${x.toFixed(1)}" y2="${y.toFixed(1)}" />
        <circle class="orientation-axis-end" cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="4" />
        <text class="orientation-axis-label" x="${labelX.toFixed(1)}" y="${labelY.toFixed(1)}" text-anchor="middle" dominant-baseline="middle">${axis.label}</text>
        <title>${t('axisTitle').replace('{axis}', axis.label).replace('{view}', axis.title)}</title>
      </g>
    `;
  }).join('');

  const orientationStatus = state.activeOrientationLabel
    ? `<text class="orientation-axis-preset-label" x="722" y="172" text-anchor="middle">${state.activeOrientationLabel}</text>`
    : `<text class="orientation-axis-angle-label" x="722" y="156" text-anchor="middle">
        <tspan x="722">${t('yawLabel')} ${displayYawDegrees(state.rotation3d.yaw)}°</tspan>
        <tspan x="722" dy="16">${t('pitchLabel')} ${Math.round(state.rotation3d.pitch)}°</tspan>
      </text>`;

  return `
    <g class="orientation-axis-control" aria-label="${t('orientationAxisControl')}">
      <rect class="orientation-axis-panel" x="648" y="18" width="148" height="184" rx="16" />
      <text class="orientation-axis-heading" x="722" y="40" text-anchor="middle">${t('orientation').toLowerCase()}</text>
      ${axisMarkup}
      ${orientationStatus}
    </g>
  `;
}

function renderSeatEncroachmentWedge3d(zone, project) {
  const rawVertices = createSeatEncroachmentWedgeVertices(zone);
  if (rawVertices.length === 0) return [];
  const vertices = rawVertices.map(project);
  const title = t('seatWedgeTitle').replace('{angle}', String(seatBackAngleDegrees(zone)));
  return [
    renderFace(vertices, [0, 1, 2], '#fecaca', 'seat-encroachment-face', title),
    renderFace(vertices, [3, 5, 4], '#fecaca', 'seat-encroachment-face', title),
    renderFace(vertices, [1, 4, 5, 2], '#fee2e2', 'seat-encroachment-face', title),
    renderFace(vertices, [0, 3, 4, 1], '#fecaca', 'seat-encroachment-face', title),
    renderFace(vertices, [0, 2, 5, 3], '#fee2e2', 'seat-encroachment-face', title)
  ];
}

function renderSeatGuide3d(zone, project) {
  const dimensions = zone.dimensionsMm;
  const seatDepth = Math.max(90, dimensions.length * 0.12);
  const seatHeight = Math.min(Math.max(360, dimensions.height * 0.82), dimensions.height + 140);
  const seatWidth = dimensions.width * 0.28;
  const gap = dimensions.width * 0.08;
  const startY = (dimensions.width - seatWidth * 2 - gap) / 2;

  return [0, 1].flatMap((index) => {
    const vertices = createBoxVertices(
      { x: dimensions.length + seatDepth * 0.15, y: startY + index * (seatWidth + gap), z: 0 },
      { length: seatDepth, width: seatWidth, height: seatHeight }
    ).map(project);

    return [
      renderFace(vertices, [0, 1, 2, 3], '#fde68a', 'seat-face', t('seatGuideTitle')),
      renderFace(vertices, [3, 0, 4, 7], '#fef3c7', 'seat-face', t('seatGuideTitle')),
      renderFace(vertices, [4, 5, 6, 7], '#fef3c7', 'seat-face', t('seatGuideTitle'))
    ];
  });
}

function renderZone3dSvg(zone, placements) {
  const svgWidth = 820;
  const svgHeight = 440;
  const padding = 34;
  const seatGuidePoints = createSeatGuideVertices(zone);
  const seatEncroachmentWedgePoints = createSeatEncroachmentWedgeVertices(zone);
  const project = createProjector(zone, placements, svgWidth, svgHeight, padding, current3dAngles(), [...seatGuidePoints, ...seatEncroachmentWedgePoints]);
  const zoneVertices = createBoxVertices({ x: 0, y: 0, z: 0 }, zone.dimensionsMm).map(project);
  const faces = [
    ...renderSeatGuide3d(zone, project),
    ...renderSeatEncroachmentWedge3d(zone, project),
    renderFace(zoneVertices, [0, 1, 2, 3], '#dbeafe', 'zone-face zone-face--floor'),
    ...placements.flatMap((placement) => {
      const color = colorForPlacement(placement);
      const vertices = createBoxVertices(placement.positionMm, placement.orientationMm).map(project);
      const title = `${localizedPlacementLabel(placement)}: ${dimensionsLabel(placement.orientationMm)}`;
      return [
        renderFace(vertices, [0, 1, 2, 3], shadeColor(color, -18), 'bag-face', title),
        renderFace(vertices, [0, 1, 5, 4], shadeColor(color, -8), 'bag-face', title),
        renderFace(vertices, [1, 2, 6, 5], shadeColor(color, -14), 'bag-face', title),
        renderFace(vertices, [2, 3, 7, 6], shadeColor(color, 2), 'bag-face', title),
        renderFace(vertices, [3, 0, 4, 7], shadeColor(color, -22), 'bag-face', title),
        renderFace(vertices, [4, 5, 6, 7], shadeColor(color, 12), 'bag-face', title)
      ];
    })
  ].sort((a, b) => a.depth - b.depth).map((face) => face.markup).join('');

  return `
    <article class="zone-card zone-card--3d">
      <div class="zone-card__header">
        <div>
          <strong>${localizeEntity(zone, 'label')}</strong>
          <span>${dimensionsLabel(zone.dimensionsMm)} · ${zone.volumeLitres} L</span>
        </div>
        <span>${t('dragHint')}</span>
      </div>
      <svg class="zone-3d-svg" viewBox="0 0 ${svgWidth} ${svgHeight}" role="img" aria-label="${localizeEntity(zone, 'label')} ${t('zone3dAria')}">
        <rect x="0" y="0" width="${svgWidth}" height="${svgHeight}" rx="18" fill="#f8fafc" />
        ${faces}
        <polyline class="zone-wire" points="${polygonPoints([zoneVertices[0], zoneVertices[1], zoneVertices[2], zoneVertices[3], zoneVertices[0]])}" />
        <line class="zone-wire" x1="${zoneVertices[0].x}" y1="${zoneVertices[0].y}" x2="${zoneVertices[4].x}" y2="${zoneVertices[4].y}" />
        <line class="zone-wire" x1="${zoneVertices[1].x}" y1="${zoneVertices[1].y}" x2="${zoneVertices[5].x}" y2="${zoneVertices[5].y}" />
        <line class="zone-wire" x1="${zoneVertices[2].x}" y1="${zoneVertices[2].y}" x2="${zoneVertices[6].x}" y2="${zoneVertices[6].y}" />
        <line class="zone-wire" x1="${zoneVertices[3].x}" y1="${zoneVertices[3].y}" x2="${zoneVertices[7].x}" y2="${zoneVertices[7].y}" />
        <polyline class="zone-wire" points="${polygonPoints([zoneVertices[4], zoneVertices[5], zoneVertices[6], zoneVertices[7], zoneVertices[4]])}" />
        ${renderOrientationAxisControl()}
      </svg>
      ${placements.length === 0 ? `<p class="empty-zone">${t('noBagsInZone')}</p>` : ''}
    </article>
  `;
}

const { renderMetricsHeader, renderMetricsLoadError } = createMetricsHeaderRenderer({ $, createEl, t, localizeEntity });
const renderVisualization = createVisualizationRenderer({
  state,
  visualization,
  setSanitizedMarkup,
  renderZoneSvg,
  renderZone3dSvg
});
const renderLists = createListsRenderer({ $, createEl, t, colorForSourceId, localizedPlacementLabel, localizedZoneLabel });

const RENDER_REGIONS_BY_CHANGE_KEY = Object.freeze({
  estimator: ['metrics', 'visualization', 'lists', 'controls', 'warnings'],
  view: ['visualization'],
  orientation3d: ['visualization'],
  localization: ['metrics', 'visualization', 'lists']
});
let estimatorModel = null;

function createEstimatorSnapshot() {
  const vehicle = selectedVehicle();
  const config = selectedConfiguration(vehicle);
  const zones = config.cargoZoneIds.map((id) => vehicle.cargoZones.find((zone) => zone.id === id)).filter(Boolean);
  const luggageSet = cloneLuggageWithQuantities();
  const options = {
    considerSeatBackEncroachment: hasActiveSeatBackEncroachment(zones),
    seatBackAngleDegrees: state.seatBackEncroachmentAngleDegrees,
    defaultUsableFraction: (100 - state.usableVolumeBufferPercent) / 100
  };
  const key = JSON.stringify({
    vehicleId: vehicle.id,
    configurationId: config.id,
    luggageSet,
    options
  });
  return { key, vehicle, config, luggageSet, options };
}

function derivedEstimatorModel() {
  const snapshot = createEstimatorSnapshot();
  if (!estimatorModel || estimatorModel.key !== snapshot.key) {
    estimatorModel = {
      ...snapshot,
      result: estimateFit(snapshot.luggageSet, snapshot.vehicle, snapshot.config.id, snapshot.options)
    };
  }
  return estimatorModel;
}

function renderResults(changeKey = 'estimator') {
  const regions = RENDER_REGIONS_BY_CHANGE_KEY[changeKey] ?? RENDER_REGIONS_BY_CHANGE_KEY.estimator;
  const { vehicle, config, result } = derivedEstimatorModel();
  if (regions.includes('metrics')) renderMetricsHeader(vehicle, config, result);
  if (regions.includes('visualization')) renderVisualization(vehicle, config, result);
  if (regions.includes('lists')) renderLists(result);
  if (regions.includes('controls')) syncCustomBagControlState(result);
  if (regions.includes('warnings')) $('#warnings').replaceChildren();
}

function applyStaticTranslations() {
  document.title = t('pageTitle');
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const key = el.dataset.i18n;
    el.textContent = t(key);
  });
  document.querySelectorAll('[data-i18n-aria-label]').forEach((el) => {
    const key = el.dataset.i18nAriaLabel;
    el.setAttribute('aria-label', t(key));
  });
  document.querySelectorAll('[data-i18n-mailto-subject]').forEach((el) => {
    const key = el.dataset.i18nMailtoSubject;
    const address = el.dataset.mailtoAddress;
    el.setAttribute('href', `mailto:${address}?subject=${encodeURIComponent(t(key))}`);
  });
}

function currentVehicleDefaults(vehicle = selectedVehicle()) {
  const defaultConfigurationId = vehicle.seatConfigurations[0]?.id ?? '';
  const defaultBufferPercent = DEFAULT_USABLE_VOLUME_BUFFER_PERCENT;
  const zones = (vehicle.seatConfigurations[0]?.cargoZoneIds ?? [])
    .map((id) => vehicle.cargoZones.find((zone) => zone.id === id))
    .filter(Boolean);
  return {
    configurationId: defaultConfigurationId,
    seatBackAngleDegrees: defaultSeatBackAngleDegrees(zones),
    usableVolumeBufferPercent: defaultBufferPercent
  };
}






const {
  persistLanguagePreference,
  getPersistedLanguagePreference,
  persistTripSetupPreference,
  applyPersistedTripSetupPreference
} = createPersistence({
  state,
  i18n: I18N,
  selectedVehicle,
  currentVehicleDefaults,
  validatePersistedTripSetupPayload,
  clamp,
  languageCookieName: LANGUAGE_COOKIE_NAME,
  languageCookieMaxAgeSeconds: LANGUAGE_COOKIE_MAX_AGE_SECONDS,
  defaultLanguage: DEFAULT_LANGUAGE,
  tripSetupCookieName: TRIP_SETUP_COOKIE_NAME,
  minSeatBackAngleDegrees: 0,
  maxSeatBackAngleDegrees: MAX_SEAT_BACK_ANGLE_DEGREES,
  minUsableVolumeBufferPercent: MIN_USABLE_VOLUME_BUFFER_PERCENT,
  maxUsableVolumeBufferPercent: MAX_USABLE_VOLUME_BUFFER_PERCENT
});

const actions = createActions({
  state,
  document,
  $,
  constants: {
    customBagId: CUSTOM_BAG_ID,
    customBagMinDimensionsMm: CUSTOM_BAG_MIN_DIMENSIONS_MM,
    customBagMaxDimensionsMm: CUSTOM_BAG_MAX_DIMENSIONS_MM,
    defaultSeatBackAngleDegrees: DEFAULT_SEAT_BACK_ANGLE_DEGREES,
    maxSeatBackAngleDegrees: MAX_SEAT_BACK_ANGLE_DEGREES,
    defaultUsableVolumeBufferPercent: DEFAULT_USABLE_VOLUME_BUFFER_PERCENT,
    minUsableVolumeBufferPercent: MIN_USABLE_VOLUME_BUFFER_PERCENT,
    maxUsableVolumeBufferPercent: MAX_USABLE_VOLUME_BUFFER_PERCENT
  },
  render: {
    elements: {
      seatBackAngleInput: seatBackEncroachmentDegreesInput,
      bufferInput: usableVolumeBufferPercentInput,
      luggageControls,
      languageSelect
    },
    boundaryStatus: updateBoundaryStatus,
    vehicleOptions: renderVehicleOptions,
    configurationOptions: renderConfigurationOptions,
    seatBackEncroachmentState: renderSeatBackEncroachmentState,
    luggageControls: renderLuggageControls,
    staticTranslations: applyStaticTranslations,
    activeViewTab(view) {
      document.querySelectorAll('.view-tab').forEach((tab) => tab.classList.toggle('active', tab.dataset.view === view));
    },
    syncCustomBagControlState,
    results: renderResults
  },
  persistence: {
    persistLanguagePreference,
    persistTripSetupPreference
  },
  validConfigurationId() {
    return selectedConfiguration().id;
  },
  defaultSeatBackAngleForSelection,
  orientationPresets
});

const bindEvents = createEventBindings({
  document,
  window,
  elements: {
    vehicleSelect,
    configurationSelect,
    seatBackAngleInput: seatBackEncroachmentDegreesInput,
    bufferInput: usableVolumeBufferPercentInput,
    resetLuggageButton,
    luggageControls,
    placedList,
    unplacedList,
    languageSelect,
    visualization
  },
  actions
});

async function renderBuildVersion() {
  const appVersionEl = $('#appVersion');
  if (!appVersionEl) return;
  try {
    const version = await readJson('./version.json');
    if (!version?.displayVersion || !version?.fullSha) return;
    appVersionEl.innerHTML = '';
    const label = document.createElement('span');
    label.textContent = 'Version: ';
    const link = document.createElement('a');
    link.href = version.githubCommitUrl || '#';
    link.textContent = version.displayVersion;
    link.target = '_blank';
    link.rel = 'noopener noreferrer';
    link.title = version.fullSha;
    appVersionEl.append(label, link);
  } catch (error) {
    console.warn('Unable to load version metadata', error);
  }
}

export async function bootstrap() {
  try {
    const [luggageSet, vehicles] = await Promise.all([
      readJson('./configs/luggage/common.json'),
      loadVehicles()
    ]);
    state.luggageSet = luggageSet;
    state.vehicles = vehicles.sort((a, b) => vehicleLabel(a).localeCompare(vehicleLabel(b)));
    const initialVehicle = defaultVehicle();
    state.vehicleId = initialVehicle.id;
    state.configurationId = initialVehicle.seatConfigurations[0].id;
    actions.resetSeatBackAngleToDefault();
    applyPersistedTripSetupPreference();
    renderVehicleOptions();
    renderConfigurationOptions();
    renderSeatBackEncroachmentState();
    renderLuggageControls();
    await renderBuildVersion();
    bindEvents();
    const persistedLanguage = getPersistedLanguagePreference();
    if (persistedLanguage && persistedLanguage !== state.language) {
      actions.setLanguage(persistedLanguage);
      return;
    }
    applyStaticTranslations();
    renderSeatBackEncroachmentState();
    renderResults();
  } catch (error) {
    renderMetricsLoadError(error.message);
    console.error(error);
  }
}
